# Generated by Django 6.0.2 on 2026-02-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=100, verbose_name='Введите имя для регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeRev', models.CharField(choices=[('Отличный Тур', 'Отличный Тур'), ('Хороший Тур', 'Хороший Тур'), ('Нормальный Тур', 'Нормальный Тур'), ('Ожидал большего', 'Ожидал большего'), ('Ужасный Тур', 'Ужасный Тур')], max_length=100)),
                ('data_rev', models.DateTimeField(auto_now_add=True)),
                ('revPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='relation_db.person')),
            ],
        ),
        migrations.CreateModel(
            name='TourPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.CharField(max_length=100)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relation_db.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='typePerson',
            field=models.ManyToManyField(blank=True, to='relation_db.type'),
        ),
    ]
