# Generated by Django 6.0.2 on 2026-02-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите названия книги')),
                ('description', models.TextField(verbose_name='Укажите описания книги')),
                ('image', models.ImageField(upload_to='imgBook/', verbose_name='Загрузите картинку книги')),
                ('created_date', models.PositiveIntegerField(null=True, verbose_name='Укажите дату выхода книги')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('viki_bok', models.URLField(null=True, verbose_name='Укажите ссылку на википедию')),
                ('book_files', models.FileField(null=True, upload_to='files/', verbose_name='Загрузите файл книги')),
            ],
            options={
                'verbose_name': 'Книга и ее описание',
                'verbose_name_plural': 'Книги и их описание',
            },
        ),
    ]
